### ISSUE TITLE
API is down (Jan/2/2023)

### ISSUE THREAD

**Issue by ehtashamparity** [meetDeveloper/freeDictionaryAPI#173] opened 2023-01-02 07:05 UTC
We can't make any GET requests, also the search bar on the official API website is not working.

Any expected time to resolve this issue  ?

**Comment by M-NabeelAli** [comment] 2023-01-02 07:08
API is not working...

**Comment by sdip15fa** [comment] 2023-01-02 08:38
duplicate of #172

**Closed as completed** 2023-02-19 02:49 UTC
